{
 "title": "DOM vSAN ESA: Capacity Fullness",
 "tags": [
  "vSAN Client",
  "vsan-overview-dom_vsan-esa"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*vsan-esa-dom-capacity-fullness\"/"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "State of scheduler",
     "measurement": "state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Target/Free Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Freeing rate",
     "measurement": "freeingRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Target rate",
     "measurement": "targetRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Token Weight",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Current weight for bank writes",
     "measurement": "tokenWeight",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Token Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Max tokens allowed",
     "measurement": "maxTokensAllowed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Currently available tokens",
     "measurement": "availTokens",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Tokens consumed by bank",
     "measurement": "tokensConsumedRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Bank IOPS Unthrottled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Bank unthrottled IOPS",
     "measurement": "unthrottledBankIOPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Prev fullness (per-mille)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Prev fullness",
     "measurement": "diskFullnessPermil",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}