{
 "title": "DOM vSAN ESA: Disks Capacity Tier",
 "tags": [
  "vSAN Client",
  "vsan-overview-dom_vsan-esa"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"host\" where entityType =~ /\"*vsan2-dom-scheduler-capacity\"/"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*vsan2-dom-scheduler-capacity\"/ and host =~ /^$host$/"
   }
  ]
 },
 "panels": [
  { "title": "$disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "disk" },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "iopsReadCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "iopsWriteCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Unmap",
     "measurement": "iopsUnmapCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Recovery Write",
     "measurement": "iopsRecoveryWriteCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Recovery Unmap",
     "measurement": "iopsRecoveryUnmapCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "throughputReadCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "throughputWriteCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Unmap",
     "measurement": "throughputUnmapCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Recovery Write",
     "measurement": "throughputRecoveryWriteCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Recovery Unmap",
     "measurement": "throughputRecoveryUnmapCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "latencyReadCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "latencyWriteCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Unmap",
     "measurement": "latencyUnmapCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Recovery Write",
     "measurement": "latencyRecoveryWriteCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Recovery Unmap",
     "measurement": "latencyRecoveryUnmapCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "OIO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "oioReadCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "oioWriteCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Unmap",
     "measurement": "oioUnmapCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Recovery Write",
     "measurement": "oioRecoveryWriteCompMgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Recovery Unmap",
     "measurement": "latencyAvgRecUnmap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  }
 ]
}