{
 "title": "LSOM: Cache Disk Details",
 "tags": [ "vSAN Client" ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"host\" where entityType =~ /\"*cache-disk\"/"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*cache-disk\"/ and host =~ /^$host$/"
   }
  ]
 },
 "panels": [
  { "title": "Device IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read IOPS",
     "measurement": "iopsDevRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write IOPS",
     "measurement": "iopsDevWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Device Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Device Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "throughputDevRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "throughputDevWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Device Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Device Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "DAVG",
     "measurement": "latencyDevDAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "KAVG",
     "measurement": "latencyDevKAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "GAVG",
     "measurement": "latencyDevGAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RDLAT",
     "measurement": "latencyDevRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WRLAT",
     "measurement": "latencyDevWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WRLAT-LE",
     "measurement": "latencyWriteLE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Device Latency (MAX)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Device Latency (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "RDLAT-MAX",
     "measurement": "latencyDevReadMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WRLAT-MAX",
     "measurement": "latencyDevWriteMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Device Latency (MIN)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Device Latency (MIN)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "RDLAT-MIN",
     "measurement": "latencyDevReadMin",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WRLAT-MIN",
     "measurement": "latencyDevWriteMin",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Disk Group IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Disk Group IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read IOPS",
     "measurement": "iopsRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write IOPS",
     "measurement": "iopsWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Disk Group Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Disk Group Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "throughputRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "throughputWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Disk Group Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Disk Group Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "latencyAvgRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "latencyAvgWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Congestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Congestion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Slab Congestion",
     "measurement": "slabCongestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Iops Congestion",
     "measurement": "iopsCongestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Comp Congestion",
     "measurement": "compCongestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Log Congestion",
     "measurement": "logCongestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Mem Congestion",
     "measurement": "memCongestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSD Congestion",
     "measurement": "ssdCongestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Delete Congestion",
     "measurement": "maxDeleteCongestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Log Congestion Bandwidth",
     "measurement": "bytesPerSecondBandwidth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "DiskGroup Capacity Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "DiskGroup Capacity Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "phyCapUsed",
     "measurement": "phyCapUsed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "phyCapT2",
     "measurement": "phyCapT2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "phyCapCF",
     "measurement": "phyCapCF",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "phyCapRsrvd",
     "measurement": "phyCapRsrvd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "phyCapRsrvdUsed",
     "measurement": "phyCapRsrvdUsed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Congestion during sampling period",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 }
  },
  {
   "title": "Max Congestion during sampling period",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "slabCongestionLocalMax",
     "measurement": "slabCongestionLocalMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "iopsCongestionLocalMax",
     "measurement": "iopsCongestionLocalMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "compCongestionLocalMax",
     "measurement": "compCongestionLocalMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "logCongestionLocalMax",
     "measurement": "logCongestionLocalMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "memCongestionLocalMax",
     "measurement": "memCongestionLocalMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "ssdCongestionLocalMax",
     "measurement": "ssdCongestionLocalMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "oobLogCongestionIOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "oobLogCongestionIOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "oobLogCongestionIOPS",
     "measurement": "oobLogCongestionIOPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Over write Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Over write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Overwrite Xput",
     "measurement": "overwritesIops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "overWriteFactorData", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "overWriteFactorData",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "overWriteFactorMovingAvg",
     "measurement": "overWriteFactorMovingAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "currentOverWriteFactor",
     "measurement": "currentOverWriteFactor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "oobLogCongestionMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "oobLogCongestionMetrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "currentTrueWBFillRate",
     "measurement": "currentTrueWBFillRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "currentDrainRate",
     "measurement": "currentDrainRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "currentIncomingRate",
     "measurement": "currentIncomingRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Write Buffer Entry Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 } },
  {
   "title": "Write Buffer Entry Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Prep Table",
     "measurement": "prepTblCnt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Commit Table",
     "measurement": "commitTblCnt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Buffer usage (percentage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 }
  },
  {
   "title": "Write Buffer usage (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "WB Free Pct",
     "measurement": "wbFreePct",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "LLOG Log Space",
     "measurement": "llogLogSpace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "LLOG Data Space",
     "measurement": "llogDataSpace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "PLOG Log Space",
     "measurement": "plogLogSpace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "PLOG Data Space",
     "measurement": "plogDataSpace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Data Elev Start Threshold",
     "measurement": "elevStartThresh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Data Elev Unthrottle Threshold",
     "measurement": "elevUnthrottleThresh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Zero Elev Start Threshold",
     "measurement": "zeroElevStartThreshold",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Zero Elev Unthrottle Threshold",
     "measurement": "zeroElevUnthrottleThreshold",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Write Buffer Usage (bytes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "Write Buffer Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "WB size",
     "measurement": "wbSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "LLOG Log",
     "measurement": "llogLog",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "LLOG Data",
     "measurement": "llogData",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "PLOG Log",
     "measurement": "plogLog",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "PLOG Data",
     "measurement": "plogData",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Bytes Overwritten",
     "measurement": "bytesOverwritten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Elev throttling params", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "Elev throttling params",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "logP",
     "measurement": "logP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "memP",
     "measurement": "memP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "ssdP",
     "measurement": "ssdP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "dataP",
     "measurement": "dataP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "zeroP",
     "measurement": "zeroP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "maxP",
     "measurement": "maxP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "zeroElevMaxP",
     "measurement": "zeroElevMaxP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Elevator throttling sleep time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 } },
  {
   "title": "Elevator throttling sleep time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Data Elev Sleep Time",
     "measurement": "timeToSleepMs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": " Zero Elev Sleep Time",
     "measurement": "zeroElevTimeToSleepMs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Destage sampling correction (available only in verbose mode)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 220 }
  },
  {
   "title": "Destage sampling correction (available only in verbose mode)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Sample Window",
     "measurement": "destageSampleTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Time slept in window",
     "measurement": "timeSleptInSample",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Elevator Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 } },
  {
   "title": "Elevator Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "TotalDrained",
     "measurement": "plogTotalBytesDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSDDrained",
     "measurement": "plogSsdBytesDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "ZeroDrained",
     "measurement": "plogZeroBytesDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Total",
     "measurement": "plogTotalTputDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSD",
     "measurement": "plogSsdTputDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Zeros",
     "measurement": "plogZeroTputDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Elevator Advertized Capability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 242 } },
  {
   "title": "Elevator Advertized Capability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Current Data Destage",
     "measurement": "advtDataDestageRateCur",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Avg Data Destage",
     "measurement": "advtDataDestageRateAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Current Zeros Destage",
     "measurement": "advtZeroDestageRateCur",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Avg Zeros Destage",
     "measurement": "advtZeroDestageRateAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 253 } },
  {
   "title": "PLOG Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "Read Queue",
     "measurement": "plogReadQLatency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write Queue",
     "measurement": "plogWriteQLatency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Total Read",
     "measurement": "plogtotalRdLat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Total Write",
     "measurement": "plogtotalWrLat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Helper Q Write",
     "measurement": "plogHelpRdQLat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Helper Q Read",
     "measurement": "plogHelpWrQLat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "DDP Scheduling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 264 } },
  {
   "title": "DDP Scheduling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Idle",
     "measurement": "avgIdleTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Pre-Read",
     "measurement": "avgPreReadTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG Cumulative Enc Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 } },
  {
   "title": "PLOG Cumulative Enc Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "Enc Read",
     "measurement": "plogCumlEncRdLat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Enc Write",
     "measurement": "plogCumlEncWrLat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG Average Queue Depth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 286 } },
  {
   "title": "PLOG Average Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 287 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Helper WQ",
     "measurement": "plogHelpRdQDepth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Helper RQ",
     "measurement": "plogHelpWrQDepth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG Read Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 } },
  {
   "title": "PLOG Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Total",
     "measurement": "plogTotalBytesRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "MD",
     "measurement": "plogTotalBytesReadFromMD",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSD",
     "measurement": "plogTotalBytesReadFromSSD",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RC",
     "measurement": "plogTotalBytesReadByRC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "VMFS",
     "measurement": "plogTotalBytesReadByVMFS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Total",
     "measurement": "plogTotalTputRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "MD",
     "measurement": "plogTotalTputReadFromMD",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSD",
     "measurement": "plogTotalTputReadFromSSD",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RC",
     "measurement": "plogTotalTputReadByRC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "VMFS",
     "measurement": "plogTotalTputReadByVMFS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG ReadOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 308 } },
  {
   "title": "PLOG ReadOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 309 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Total",
     "measurement": "plogNumTotalReads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "MD",
     "measurement": "plogNumMDReads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSD",
     "measurement": "plogNumSSDReads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RC",
     "measurement": "plogNumRCReads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "VMFS",
     "measurement": "plogNumVMFSReads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Total",
     "measurement": "plogNumTotalReadOPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "MD",
     "measurement": "plogNumMDReadOPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSD",
     "measurement": "plogNumSSDReadOPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RC",
     "measurement": "plogNumRCReadOPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "VMFS",
     "measurement": "plogNumVMFSReadOPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG Data Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 319 } },
  {
   "title": "PLOG Data Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 320 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "DGData",
     "measurement": "plogDGDataUsage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG Write Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 330 } },
  {
   "title": "PLOG Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 331 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "CS",
     "measurement": "plogTotalCSBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Zero",
     "measurement": "plogTotalZeroBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Delete",
     "measurement": "plogTotalDelBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "fsBytes",
     "measurement": "plogTotalFSBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "cfBytes",
     "measurement": "plogTotalCFBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "fsUnmapBytes",
     "measurement": "plogTotalFSUnmapBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "cfUnmapBytes",
     "measurement": "plogTotalCFUnmapBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "CS",
     "measurement": "plogTotalCSTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Zero",
     "measurement": "plogTotalZeroTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Delete",
     "measurement": "plogTotalDelTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "fsBytes",
     "measurement": "plogTotalFSTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "cfBytes",
     "measurement": "plogTotalCFTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "fsUnmapBytes",
     "measurement": "plogTotalFSUnmapTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "cfUnmapBytes",
     "measurement": "plogTotalCFUnmapTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 341 } },
  {
   "title": "PLOG Logs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 342 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "WriteLogs",
     "measurement": "plogNumWriteLogs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "CommitLogs",
     "measurement": "plogNumCommitLogs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WriteLogsFreed",
     "measurement": "plogNumFreedLogs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "CommitLogsFreed",
     "measurement": "plogNumFreedCommitLogs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Dedup Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 352 } },
  {
   "title": "Dedup Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 353 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "dedupedBytes",
     "measurement": "dedupedBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "hashedBytes",
     "measurement": "hashedBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "dedupTput",
     "measurement": "dedupTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "hashTput",
     "measurement": "hashTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "DDP Internal Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 363 } },
  {
   "title": "DDP Internal Rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 364 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "ddpWriteRate",
     "measurement": "ddpWriteRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "ddpCommitRate",
     "measurement": "ddpCommitRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "DDP Bytes per commit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 374 } },
  {
   "title": "DDP Bytes per commit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 375 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "txnSizePerCommit",
     "measurement": "txnSizePerCommit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "mappedBytesPerCommit",
     "measurement": "mappedBytesPerCommit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Dedup Run Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 385 } },
  {
   "title": "Dedup Run Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 386 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "txnBuildTime",
     "measurement": "txnBuildTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "txnWriteTime",
     "measurement": "txnWriteTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "txnReplayTime",
     "measurement": "txnReplayTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "hashCalcTime",
     "measurement": "hashCalcTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "compressionTime",
     "measurement": "compressionTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "dataWriteTime",
     "measurement": "dataWriteTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "txnReplayHashmapTime",
     "measurement": "txnReplayHashmapTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "txnReplayXmapTime",
     "measurement": "txnReplayXmapTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "txnReplayBitmapTime",
     "measurement": "txnReplayBitmapTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Dedup Metadata IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 396 } },
  {
   "title": "Dedup Metadata IO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 397 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "numHashmapRd",
     "measurement": "numHashmapRd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "numHashmapWrt",
     "measurement": "numHashmapWrt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "numBitmapRd",
     "measurement": "numBitmapRd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "numBitmapWrt",
     "measurement": "numBitmapWrt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "numXMapRd",
     "measurement": "numXMapRd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "numXMapWrt",
     "measurement": "numXMapWrt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Dedup Percentages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 407 } },
  {
   "title": "Dedup Percentages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 408 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "dedupPct",
     "measurement": "dedupPct",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "dedupCcheHitRt",
     "measurement": "dedupCcheHitRt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "compressPct",
     "measurement": "compressPct",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Dedup Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 418 } },
  {
   "title": "Dedup Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 419 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "ddpTotalCap",
     "measurement": "ddpTotalCap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "ddpFreeCap",
     "measurement": "ddpFreeCap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Dedup Txn Replay Optimization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 429 } },
  {
   "title": "Dedup Txn Replay Optimization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 430 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pendingTxnReplayYields",
     "measurement": "pendingTxnReplayYields",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "txnReplayWriteIOs",
     "measurement": "txnReplayWriteIOs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "txnReplayReadIOHits",
     "measurement": "txnReplayReadIOHits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "LLOG Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 440 } },
  {
   "title": "LLOG Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 441 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "RC Read",
     "measurement": "latencyRcRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WB Read",
     "measurement": "latencyWbRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RC Write",
     "measurement": "latencyRcWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WB Write",
     "measurement": "latencyWbWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RC Read Queue",
     "measurement": "latencyRcRdQ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RC Write Queue",
     "measurement": "latencyRcWrtQ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WB Read Queue",
     "measurement": "latencyWbRdQ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WB Write Queue",
     "measurement": "latencyWbWrtQ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "LLOG IOPs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 451 } },
  {
   "title": "LLOG IOPs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 452 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "RC Read",
     "measurement": "iopsRcRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WB Read",
     "measurement": "iopsWbRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RC Write",
     "measurement": "iopsRcWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WB Write",
     "measurement": "iopsWbWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Block attribute cache size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 462 } },
  {
   "title": "Block attribute cache size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 463 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "alias": "blkAttrCcheSz",
     "measurement": "blkAttrCcheSz",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Blk Attr cache hit rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 473 } },
  {
   "title": "Blk Attr cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 474 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "blkAttrCcheHitRt",
     "measurement": "blkAttrCcheHitRt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Compressed Blocks in Dedup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 484 } },
  {
   "title": "Compressed Blocks in Dedup",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 485 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "numCompressedHashBlocks",
     "measurement": "numCompressedHashBlocks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Dedup IO Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 495 } },
  {
   "title": "Dedup IO Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 496 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "numDdpMetadataReads",
     "measurement": "numDdpMetadataReads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "numDdpMetadataWrites",
     "measurement": "numDdpMetadataWrites",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "numGuestReads",
     "measurement": "numGuestReads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Checksum Error (& Corrected)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 506 } },
  {
   "title": "Checksum Error (& Corrected)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 507 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "checksumErrors",
     "measurement": "checksumErrors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "totalDATABlksCorrected",
     "measurement": "totalDATABlksCorrected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "totalCRCCorrected",
     "measurement": "totalCRCCorrected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "PLOG Zero Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 517 } },
  {
   "title": "PLOG Zero Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 518 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "DGZero",
     "measurement": "plogDGZeroUsage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  }
 ]
}