{
 "title": "Memory: Heaps and Slabs",
 "tags": [
  "vSAN Client",
  "vsan-overview"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"host\" where entityType =~ /\"*host-memory-.*\"/"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Slab Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "slabUtil",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"host-memory-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Slab Allocation Failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "slabAllocFailures",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"host-memory-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "heapUtil",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"host-memory-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap Allocation Failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "heapAllocFailures",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"host-memory-.*\"/"
      }
     ]
    }
   ]
  }
 ]
}