{
 "title": "Networking: TCP IP",
 "tags": [
  "vSAN Client",
  "vsan-overview-network"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*vsan-vnic-net\"/"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Packets/sec (average)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "tcpRxPackets",
     "measurement": "tcpRxPackets",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpTxPackets",
     "measurement": "tcpTxPackets",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput (average)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "tcpRxThroughput",
     "measurement": "tcpRxThroughput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpTxThroughput",
     "measurement": "tcpTxThroughput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Connections (ikb 57375)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "tcpKeeptimeo",
     "measurement": "tcpKeeptimeo",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpPersisttimeo",
     "measurement": "tcpPersisttimeo",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRexmttimeo",
     "measurement": "tcpRexmttimeo",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpTimeoutdrop",
     "measurement": "tcpTimeoutdrop",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpConndrops",
     "measurement": "tcpConndrops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpDrops",
     "measurement": "tcpDrops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpKeepdrops",
     "measurement": "tcpKeepdrops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvmemdrop",
     "measurement": "tcpRcvmemdrop",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpConnects",
     "measurement": "tcpConnects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpHalfopenDropRate",
     "measurement": "tcpHalfopenDropRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpTimeoutDropRate",
     "measurement": "tcpTimeoutDropRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Transmission (ikb 57375)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "tcpSndacks",
     "measurement": "tcpSndacks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvackpack",
     "measurement": "tcpRcvackpack",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvduppack",
     "measurement": "tcpRcvduppack",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvoopack",
     "measurement": "tcpRcvoopack",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvdupack",
     "measurement": "tcpRcvdupack",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpSackRexmits",
     "measurement": "tcpSackRexmits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpSackSendBlocks",
     "measurement": "tcpSackSendBlocks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpSackRcvBlocks",
     "measurement": "tcpSackRcvBlocks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpTxRexmitRate",
     "measurement": "tcpTxRexmitRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvdupackRate",
     "measurement": "tcpRcvdupackRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvoopackRate",
     "measurement": "tcpRcvoopackRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvduppackRate",
     "measurement": "tcpRcvduppackRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpSackSendBlocksRate",
     "measurement": "tcpSackSendBlocksRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpSackRcvBlocksRate",
     "measurement": "tcpSackRcvBlocksRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpSackRexmitsRate",
     "measurement": "tcpSackRexmitsRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP/IP Errors (per-mille)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "tcpBadsyn",
     "measurement": "tcpBadsyn",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpBadrst",
     "measurement": "tcpBadrst",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvbadsum",
     "measurement": "tcpRcvbadsum",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvbadoff",
     "measurement": "tcpRcvbadoff",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpRcvshort",
     "measurement": "tcpRcvshort",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpErrs",
     "measurement": "tcpErrs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ipErrs",
     "measurement": "ipErrs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ip6Errs",
     "measurement": "ip6Errs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Congestion (average)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "tcpSndZeroWin",
     "measurement": "tcpSndZeroWin",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tcpEcnCe",
     "measurement": "tcpEcnCe",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}