{
 "title": "RDT: Info",
 "tags": [
  "vSAN Client",
  "vsan-overview-rdt"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"host\" where entityType =~ /\"*rdt-.*\"/"
   }
  ]
 },
 "panels": [
  {
   "title": "Checksum Mismatch Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "checksumMismatchCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Association Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "assocCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Maximum Association Count Reached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "maxAssocCountReached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "RDT Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "rdtConnCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Maximum RDT Connection Count Reached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "maxRDTConnCountReached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes transferred",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "totalTxBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Maximum Bytes transferred",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "maxTxBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes Recieved",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "totalRxBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  },
  {
   "title": "Maximum Bytes Recieved",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "maxRxBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=~",
       "value": "/\"rdt-.*\"/"
      }
     ]
    }
   ]
  }
 ]
}