{
 "title": "CLOM: Disk Stats",
 "tags": [
  "vSAN Client",
  "vsan-overview-clom"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"host\" where entityType =~ /\"*clom-disk-stats\"/"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*clom-disk-stats\"/ and host =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "diskCompCntRatio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "diskCompCntRatio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "diskDataCompCntRatio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "diskDataCompCntRatio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "diskgrpDataCompCntRatio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "diskgrpDataCompCntRatio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "nodeCompCntRatio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "nodeCompCntRatio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "nodeDataCompCntRatio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "nodeDataCompCntRatio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "diskFullness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "diskFullness",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "updatesApplied",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "updatesApplied",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "updatesRequested",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "updatesRequested",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "fitness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "fitness",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "maxActResvSpaceUtil",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "maxActResvSpaceUtil",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "placementGroup",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "placementGroup",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "rcResvUtil",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "rcResvUtil",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "resourceStddevChange",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "resourceStddevChange",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "unresvAddrSpaceUtil",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "unresvAddrSpaceUtil",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "usageVariance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "usageVariance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "versionWeight",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "versionWeight",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  }
 ]
}