{
 "title": "CLOM: Disk Fullness Stats",
 "tags": [
  "vSAN Client",
  "vsan-overview-clom"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"host\" where entityType =~ /\"*clom-disk-fullness-stats\"/"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*clom-disk-fullness-stats\"/ and host =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "physFreeCapacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "physFreeCapacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "physFullness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "physFullness",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "logicalFullness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "logicalFullness",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "transientCapacityUsed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "transientCapacityUsed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "rebalFullness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "rebalFullness",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "dedupRatio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "dedupRatio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "pendingWrites",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "pendingWrites",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "pendingDelete",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "pendingDelete",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "logicalCapacityRequested",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "logicalCapacityRequested",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "physDiskCapacityReserved",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "physDiskCapacityReserved",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "actualBytesSchedToMove",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "actualBytesSchedToMove",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "actualBytesMoving",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "actualBytesMoving",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "rebalStatus",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "rebalStatus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "numComponents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "numComponents",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  }
 ]
}