{
 "title": "CMMDS: Workload Stats",
 "tags": [
  "vSAN Client",
  "vsan-overview-cmmds"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*cmmds-workloadstats\"/"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Rx Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "rxAccept",
     "measurement": "rxAccept",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rxAgentUpdateRequest",
     "measurement": "rxAgentUpdateRequest",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rxHeartbeatRequest",
     "measurement": "rxHeartbeatRequest",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rxMasterUpdate",
     "measurement": "rxMasterUpdate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rxRetransmitRequest",
     "measurement": "rxRetransmitRequest",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rxSnapshot",
     "measurement": "rxSnapshot",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rxMisc",
     "measurement": "rxMisc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Tx Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "txAgentUpdateRequest",
     "measurement": "txAgentUpdateRequest",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txHeartbeatRequest",
     "measurement": "txHeartbeatRequest",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txMasterCheckpoint",
     "measurement": "txMasterCheckpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txMasterCkptTried",
     "measurement": "txMasterCkptTried",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txRetransmitRequest",
     "measurement": "txRetransmitRequest",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txSnapshot",
     "measurement": "txSnapshot",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txSnapshotBytes",
     "measurement": "txSnapshotBytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txSnapshotTried",
     "measurement": "txSnapshotTried",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txMasterUpdate",
     "measurement": "txMasterUpdate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txMasterUpdateTried",
     "measurement": "txMasterUpdateTried",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Batch Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "agentBatchesSent",
     "measurement": "agentBatchesSent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "totalUpdSentInAgentBatch",
     "measurement": "totalUpdSentInAgentBatch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "checkPointBatchesSent",
     "measurement": "checkPointBatchesSent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "totalUpdInBatchCkpt",
     "measurement": "totalUpdInBatchCkpt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "masterBatchesRecved",
     "measurement": "masterBatchesRecved",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "totalUpdInMasterBatches",
     "measurement": "totalUpdInMasterBatches",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}