{
 "title": "DOM vSAN & vSAN ESA: Network Scheduler",
 "tags": [
  "vSAN Client",
  "vsan-overview-dom"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*host-domowner\"/"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "DOM Network Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "Latency",
     "measurement": "numNetSchedRollingAvgLatUs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM Network Throttled Iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Owner",
     "measurement": "numNetSchedOwnerIops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp",
     "measurement": "numNetSchedCompIops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Owner RecoveryWrites",
     "measurement": "numNetSchedOwnerRecoveryWriteIops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp RecoveryWrites",
     "measurement": "numNetSchedCompRecoveryWriteIops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Owner ResyncReads",
     "measurement": "numNetSchedOwnerResyncReadIops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp ResyncReads",
     "measurement": "numNetSchedCompResyncReadIops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM Network Throttled Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Owner",
     "measurement": "numNetSchedOwnerTpThrottled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp",
     "measurement": "numNetSchedCompTpThrottled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Owner RecoveryWrite",
     "measurement": "numNetSchedOwnerRecoveryWriteTpThrottled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp RecoveryWrite",
     "measurement": "numNetSchedCompRecoveryWriteTpThrottled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Owner ResyncRead",
     "measurement": "numNetSchedOwnerResyncReadTpThrottled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp ResyncRead",
     "measurement": "numNetSchedCompResyncReadTpThrottled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM Network Applied Iops Limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Owner",
     "measurement": "numNetSchedOwnerIopsLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp",
     "measurement": "numNetSchedCompIopsLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Owner RecoveryWrite",
     "measurement": "numNetSchedOwnerRecoveryWriteIopsLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp RecoveryWrite",
     "measurement": "numNetSchedCompRecoveryWriteIopsLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Owner ResyncRead",
     "measurement": "numNetSchedOwnerResyncReadIopsLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Comp ResyncRead",
     "measurement": "numNetSchedCompResyncReadIopsLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Bands Controller when Throttling IOs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "High Bands",
     "measurement": "numNetSchedHighBand",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Middle Bands",
     "measurement": "numNetSchedMidBand",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Low Bands",
     "measurement": "numNetSchedLowdBand",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "High Band Low Limit",
     "measurement": "numNetSchedHighBandLowLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Low Band High Limit",
     "measurement": "numNetSchedLowBandHighLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Middle Band High Limit",
     "measurement": "numNetSchedMidBandHighLimit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "High Band High Share",
     "measurement": "numNetSchedHighBandHighShare",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Middle Band Low Share",
     "measurement": "numNetSchedMidBandLowShare",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Controller Activations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Activations",
     "measurement": "numNetSchedControllerActivations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}