{
 "title": "LSOM: Capacity Disk",
 "tags": [
  "vSAN Client",
  "vsan-overview-lsom"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"host\" where entityType =~ /\"*capacity-disk\"/"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*capacity-disk\"/ and host =~ /^$host$/"
   }
  ]
 },
 "panels": [
  { "title": "$disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "disk" },
  {
   "title": "Device Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "throughputDevRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "throughputDevWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "DAVG",
     "measurement": "latencyDevDAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "KAVG",
     "measurement": "latencyDevKAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "GAVG",
     "measurement": "latencyDevGAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "RDLAT",
     "measurement": "latencyDevRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WRLAT",
     "measurement": "latencyDevWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Transient Capacity Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Disk Group",
     "measurement": "dgTransientCapacityUsed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "Disk",
     "measurement": "diskTransientCapacityUsed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "PLOG Elev (aka Destage/Drain) Tput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "TotalDrained",
     "measurement": "plogTotalBytesDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSDDrained",
     "measurement": "plogSsdBytesDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "ZeroDrained",
     "measurement": "plogZeroBytesDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "TotalDrained",
     "measurement": "plogTotalTputDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "SSDDrained",
     "measurement": "plogSsdTputDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "ZeroDrained",
     "measurement": "plogZeroTputDrained",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "PLOG Data Elev Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "SSD Read",
     "measurement": "elevSSDReadLatency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "MD Write",
     "measurement": "elevMDWriteLatency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  }
 ]
}