{
 "title": "LSOM2: KVStore Stats",
 "tags": [
  "vSAN Client",
  "vsan-overview-lsom2"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*kvstore\"/"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Allocator API Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Alloc API latency",
     "measurement": "avgAllocBlockTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Free block API latency",
     "measurement": "avgFreeTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Checkpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Max Merge Bitmap Time",
     "measurement": "cpMaxMergeBitmapsTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Min Merge Bitmap Time",
     "measurement": "cpMinMergeBitmapsTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Merge Bitmap Time",
     "measurement": "cpAvgMergeBitmapsTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Process Free Lists Time",
     "measurement": "cpMaxProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Min Process Free Lists Time",
     "measurement": "cpMinProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Process Free Lists Time",
     "measurement": "cpAvgProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Cleanup Time",
     "measurement": "cpMaxCleanupTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Min Cleanup Time",
     "measurement": "cpMinCleanupTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Cleanup Time",
     "measurement": "cpAvgCleanupTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Checkpoint Time",
     "measurement": "cpMaxCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Min Checkpoint Time",
     "measurement": "cpMinCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Checkpoint Time",
     "measurement": "cpAvgCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Block Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Alloc Block Throughput",
     "measurement": "blksAllocdTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Free Block Throughput",
     "measurement": "blksFreedTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator API Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Alloc Block API Throughput",
     "measurement": "allocBlockApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Free API Throughput",
     "measurement": "freeApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Add To FreeList API Throughput",
     "measurement": "addToFreeListApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Process FreeList API Throughput",
     "measurement": "processFreeListApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Process Free List Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Min ProcessFreeList Time",
     "measurement": "minProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg ProcessFreeList Time",
     "measurement": "avgProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max ProcessFreeList Time",
     "measurement": "maxProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Alloc/Free Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Avg Free Time",
     "measurement": "freeLatencyAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Free Time",
     "measurement": "freeLatencyMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Alloc Time",
     "measurement": "allocLatencyAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Alloc Time",
     "measurement": "allocLatencyMax",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}