{
 "title": "LSOM2: Stats Details",
 "tags": [ "vSAN Client" ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"object\" where entityType =~ /\"*lsom2-io-stats\"/"
   }
  ]
 },
 "panels": [
  { "title": "LSOM2 IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LSOM2 IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read IOPS",
     "measurement": "iopsRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Write IOPS",
     "measurement": "iopsWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Unmap IOPS",
     "measurement": "iopsUnmap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Read/Write Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "LSOM2 Read/Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Read Throughput",
     "measurement": "tputRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Disk Read Throughput",
     "measurement": "tputReadDisk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Write Throughput",
     "measurement": "tputWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Unmap Throughput",
     "measurement": "tputUnmap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Read/Write Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "LSOM2 Read/Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Average Read Time",
     "measurement": "avgLatRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Average Write Time",
     "measurement": "avgLatWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Average Unmap Time",
     "measurement": "avgLatUnmap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Read/Write Latency (MAX)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "LSOM2 Read/Write Latency (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Maximum Read Time",
     "measurement": "maxReadTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Maximum Write Time",
     "measurement": "maxWriteTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Maximum Unmap Time",
     "measurement": "maxUnmapTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Read/Write Latency (MIN)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "LSOM2 Read/Write Latency (MIN)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Minimum Read Time",
     "measurement": "minReadTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Minimum Write Time",
     "measurement": "minWriteTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Minimum Unmap Time",
     "measurement": "minUnmapTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Allocator API Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Allocator API Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Alloc API latency",
     "measurement": "avgAllocBlockTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Reserve API latency",
     "measurement": "avgReserveBlockTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Finalize API latency",
     "measurement": "avgFinalizeBlockTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Free block API latency",
     "measurement": "avgFreeTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Allocator Checkpoint Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Allocator Checkpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Avg Merge Bitmap Time",
     "measurement": "cpAvgMergeBitmapsTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Process Free Lists Time",
     "measurement": "cpAvgProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Flush Pages Time",
     "measurement": "cpAvgFlushPagesTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Cleanup Time",
     "measurement": "cpAvgCleanupTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Checkpoint Time",
     "measurement": "cpAvgCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Checkpoint Latency (MAX)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }
  },
  {
   "title": "Allocator Checkpoint Latency (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Max Merge Bitmap Time",
     "measurement": "cpMaxMergeBitmapsTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Process Free Lists Time",
     "measurement": "cpMaxProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Flush Pages Time",
     "measurement": "cpMaxFlushPagesTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Cleanup Time",
     "measurement": "cpMaxCleanupTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Checkpoint Time",
     "measurement": "cpMaxCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Checkpoint Latency (MIN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 }
  },
  {
   "title": "Allocator Checkpoint Latency (MIN)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Min Merge Bitmap Time",
     "measurement": "cpMinMergeBitmapsTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Min Process Free Lists Time",
     "measurement": "cpMinProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Min Flush Pages Time",
     "measurement": "cpMinFlushPagesTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Min Cleanup Time",
     "measurement": "cpMinCleanupTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Min Checkpoint Time",
     "measurement": "cpMinCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Allocator Block Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Allocator Block Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Alloc Block Throughput",
     "measurement": "blksAllocdTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Reserve Block Throughput",
     "measurement": "blksReservedTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Finalize Block Throughput",
     "measurement": "blksFinalizedTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Free Block Throughput",
     "measurement": "blksFreedTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Allocator API Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Allocator API Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Alloc Block API Throughput",
     "measurement": "allocBlockApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Reserve Block API Throughput",
     "measurement": "reserveBlockApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Finalize Block API Throughput",
     "measurement": "finalizeBlockApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Free API Throughput",
     "measurement": "freeApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Add To FreeList API Throughput",
     "measurement": "addToFreeListApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Process FreeList API Throughput",
     "measurement": "processFreeListApiTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Reserve Blocks Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 }
  },
  {
   "title": "Allocator Reserve Blocks Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Avg Reserve Time",
     "measurement": "avgReserveBlockTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Reserve Blocks Latency (MAX)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 }
  },
  {
   "title": "Allocator Reserve Blocks Latency (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Max Reserve Time",
     "measurement": "maxReserveBlockTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Reserve Blocks Latency (MIN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 }
  },
  {
   "title": "Allocator Reserve Blocks Latency (MIN)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Min Reserve Time",
     "measurement": "minReserveBlockTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Process Free List Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 }
  },
  {
   "title": "Allocator Process Free List Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Avg ProcessFreeList Time",
     "measurement": "avgProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Process Free List Latency (MAX)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 }
  },
  {
   "title": "Allocator Process Free List Latency (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Max ProcessFreeList Time",
     "measurement": "maxProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Process Free List Latency (MIN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 }
  },
  {
   "title": "Allocator Process Free List Latency (MIN)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Min ProcessFreeList Time",
     "measurement": "minProcessFreeListTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator FreeLists Processed Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 }
  },
  {
   "title": "Allocator FreeLists Processed Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "FreeLists Processed Throughput",
     "measurement": "freeListsProcessedTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Pbas Added To FreeList Throughput",
     "measurement": "pbasAddedToFreeListTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Checkpoint Write IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 }
  },
  {
   "title": "Allocator Checkpoint Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Checkpoint Write IOPS",
     "measurement": "cpWriteIOPS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocator Checkpoint Write Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 }
  },
  {
   "title": "Allocator Checkpoint Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Checkpoint Write Throughput",
     "measurement": "cpWriteIOTput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Allocated Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 220 } },
  {
   "title": "Allocated Space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Allocated Percentage",
     "measurement": "allocatedSpace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Allocated Space Pending Free Percentage",
     "measurement": "spacePendingFree",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Capacity",
     "measurement": "capacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Component Table Checkpoint Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 242 }
  },
  {
   "title": "Component Table Checkpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Min Page Flush Time",
     "measurement": "ctFlushMinTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Avg Page Flush Time",
     "measurement": "ctFlushAvgTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max Page Flush Time",
     "measurement": "ctFlushMaxTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Component Table Checkpoint Pages Flushed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 253 }
  },
  {
   "title": "Component Table Checkpoint Pages Flushed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pages Flushed To Disk",
     "measurement": "ctNumPagesFlushed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Component Table Component Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 264 }
  },
  {
   "title": "Component Table Component Stats",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "FREE Components",
     "measurement": "ctNumFreeComp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "RESERVED Components",
     "measurement": "ctNumReservedComp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ACTIVE Components",
     "measurement": "ctNumActiveComp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "DELETED Components",
     "measurement": "ctNumDeletedComp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ZOMBIE Components",
     "measurement": "ctNumZombieComp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Failed Reserve Component IDs",
     "measurement": "ctNumFailedReserves",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Congestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 } },
  {
   "title": "LSOM2 Congestion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Global Congestion",
     "measurement": "global",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Be Data Congestion",
     "measurement": "beData",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Be Data Allocator Congestion",
     "measurement": "beDataAllocator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Be Policy Allocator Congestion",
     "measurement": "bePolicyAllocator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Write Ahead Log Congestion",
     "measurement": "wal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Write Ahead Log Allocator Congestion",
     "measurement": "walAllocator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Splinter Logical Table Congestion",
     "measurement": "splLogical",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Splinter Prepare Table Congestion",
     "measurement": "splPrepare",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Splinter Attribute Table Congestion",
     "measurement": "splAttr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Splinter Allocator Congestion",
     "measurement": "splAllocator",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 286 } },
  {
   "title": "LSOM2 Transaction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 287 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Checkpoints",
     "measurement": "numCheckpoints",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Number of Checkpoint Triggers",
     "measurement": "numCheckpointTriggers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Transaction Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 } },
  {
   "title": "LSOM2 Transaction Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Average Checkpoint Time",
     "measurement": "avgCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Transaction Time (MAX)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 308 } },
  {
   "title": "LSOM2 Transaction Time (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 309 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Max Checkpoint Time",
     "measurement": "maxCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 Transaction Time (MIN)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 319 } },
  {
   "title": "LSOM2 Transaction Time (MIN)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 320 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Min Checkpoint Time",
     "measurement": "minCheckpointTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 WAL Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 330 } },
  {
   "title": "LSOM2 WAL Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 331 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used Capacity",
     "measurement": "capacityUsed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Total Capacity",
     "measurement": "capacityTotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "LSOM2 WAL Density", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 341 } },
  {
   "title": "LSOM2 WAL Density",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 342 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Append Tput",
     "measurement": "tputAppend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Write Tput",
     "measurement": "tputWriteLsom2Partition",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Device IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 352 } },
  {
   "title": "Device IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 353 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read IOPS",
     "measurement": "iopsDevRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Write IOPS",
     "measurement": "iopsDevWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Device Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 363 } },
  {
   "title": "Device Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 364 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "measurement": "throughputDevRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Write",
     "measurement": "throughputDevWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Device Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 374 } },
  {
   "title": "Device Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 375 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "DAVG",
     "measurement": "latencyDevDAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "KAVG",
     "measurement": "latencyDevKAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "GAVG",
     "measurement": "latencyDevGAvg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "RDLAT",
     "measurement": "latencyDevRead",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "WRLAT",
     "measurement": "latencyDevWrite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}