{
 "title": "VSAN ESA Distribution",
 "tags": [
  "vSAN Client",
  "vsan-overview"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values with key=\"host\" where entityType =~ /\"*vsan-esa-distribution\"/"
   }
  ]
 },
 "panels": [
  {
   "title": "components",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "components",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=",
       "value": "\"vsan-esa-distribution\""
      }
     ]
    }
   ]
  },
  {
   "title": "ioComponents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "ioComponents",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=",
       "value": "\"vsan-esa-distribution\""
      }
     ]
    }
   ]
  },
  {
   "title": "maxComponents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "maxComponents",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=",
       "value": "\"vsan-esa-distribution\""
      }
     ]
    }
   ]
  },
  {
   "title": "domClients",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "domClients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=",
       "value": "\"vsan-esa-distribution\""
      }
     ]
    }
   ]
  },
  {
   "title": "domOwners",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "domOwners",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=",
       "value": "\"vsan-esa-distribution\""
      }
     ]
    }
   ]
  },
  {
   "title": "domColocated",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$measurement : [[tag_objKey]]",
     "groupBy": [
      { "params": [ "objKey" ], "type": "tag" }
     ],
     "measurement": "domColocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "entityType",
       "operator": "=",
       "value": "\"vsan-esa-distribution\""
      }
     ]
    }
   ]
  }
 ]
}