{
 "title": "HCIBench Fio Monitoring",
 "tags": [ "fio" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Testname", "query": "fio.*" },
   { "name": "Testcase", "query": "fio.$Testname.*" }
  ]
 },
 "panels": [
  { "title": "Fio Single Stats (Current)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(fio.$Testname.$Testcase.*.localhost.read.iops, fio.$Testname.$Testcase.*.localhost.write.iops)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(fio.$Testname.$Testcase.*.localhost.read.bw, fio.$Testname.$Testcase.*.localhost.write.bw)"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(fio.$Testname.$Testcase.*.localhost.read.lat_ns)"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(fio.$Testname.$Testcase.*.localhost.write.lat_ns)"
    }
   ]
  },
  {
   "title": "Read 95th Percentile Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(fio.$Testname.$Testcase.*.localhost.read.95tile)"
    }
   ]
  },
  {
   "title": "Write 95th Percentile Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(fio.$Testname.$Testcase.*.localhost.write.95tile)"
    }
   ]
  },
  {
   "title": "Block Size (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(fio.$Testname.$Testcase.*.localhost.bs)"
    }
   ]
  },
  {
   "title": "Number of Fio VMs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "countSeries(fio.$Testname.$Testcase.*.localhost.bs)"
    }
   ]
  },
  {
   "title": "Total Outstanding I/Os",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sum(fio.$Testname.$Testcase.*.localhost.iodepth)"
    }
   ]
  },
  {
   "title": "Read Ratio",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "target": "avg(fio.$Testname.$Testcase.*.localhost.rwmixread)"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "target": "avg(fio.$Testname.$Testcase.*.localhost.cpuload)"
    }
   ]
  },
  { "title": "Fio Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Fio IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aggregateWithWildcards(aliasByNode(fio.$Testname.$Testcase.*.localhost.*.iops, 3), 'sum')"
    }
   ]
  },
  {
   "title": "Fio Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aggregateWithWildcards(aliasByNode(fio.$Testname.$Testcase.*.localhost.*.bw, 3), 'sum')"
    }
   ]
  },
  {
   "title": "Fio Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByNode(fio.$Testname.$Testcase.*.localhost.read.lat_ns, 3)"
    }
   ]
  },
  {
   "title": "Fio Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByNode(fio.$Testname.$Testcase.*.localhost.write.lat_ns, 3)"
    }
   ]
  },
  {
   "title": "Read 95th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByNode(fio.$Testname.$Testcase.*.localhost.read.95tile, 3)"
    }
   ]
  },
  {
   "title": "Write 95th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByNode(fio.$Testname.$Testcase.*.localhost.write.95tile, 3)"
    }
   ]
  },
  {
   "title": "Fio Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(fio.$Testname.$Testcase.*.localhost.iodepth, 3)"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(fio.$Testname.$Testcase.*.localhost.cpuload, 3)"
    }
   ]
  }
 ]
}